/*Copyright (c) 2015-2016 presense@presense.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with presense@presense.com*/

package com.presense.dadjf5a027tja9;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * Beacon generated by hbm2java
 */
@Entity
@Table(name="beacon"
    ,schema="public"
)
public class Beacon  implements java.io.Serializable
 {


private String beaconId;
private Person person;

    public Beacon() {
    }



     @Id 

    

    @Column(name="beacon_id", nullable=false)
    public String getBeaconId() {
        return this.beaconId;
    }
    
    public void setBeaconId(String beaconId) {
        this.beaconId = beaconId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="person", nullable=false)
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof Beacon) )
		 return false;

		 Beacon that = ( Beacon ) o;

		 return ( (this.getBeaconId()==that.getBeaconId()) || ( this.getBeaconId()!=null && that.getBeaconId()!=null && this.getBeaconId().equals(that.getBeaconId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getBeaconId() == null ? 0 : this.getBeaconId().hashCode() );

         return result;
     }


}

