/*Copyright (c) 2015-2016 presense@presense.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with presense@presense.com*/

package com.presense.dadjf5a027tja9;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * EventmanagerId generated by hbm2java
 */
@Embeddable
public class EventmanagerId  implements java.io.Serializable
 {


private long eventId;
private String managerId;

    public EventmanagerId() {
    }




    

    @Column(name="event_id", nullable=false)
    public long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(long eventId) {
        this.eventId = eventId;
    }

    

    @Column(name="manager_id", nullable=false)
    public String getManagerId() {
        return this.managerId;
    }
    
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof EventmanagerId) )
		 return false;

		 EventmanagerId that = ( EventmanagerId ) o;

         return (this.getEventId()==that.getEventId())
 && ( (this.getManagerId()==that.getManagerId()) || ( this.getManagerId()!=null && that.getManagerId()!=null && this.getManagerId().equals(that.getManagerId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + (int) this.getEventId();
         result = 37 * result + ( getManagerId() == null ? 0 : this.getManagerId().hashCode() );

         return result;
     }


}

