/*Copyright (c) 2015-2016 presense@presense.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with presense@presense.com*/

package com.presense.dadjf5a027tja9;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * Event generated by hbm2java
 */
@Entity
@Table(name="event"
    ,schema="public"
)
public class Event  implements java.io.Serializable
 {


private long eventId;
private String name;
private Date startdate;
private Date enddate;
private Set<Attendance> attendances = new HashSet<Attendance>(0);
private Set<Eventmanager> eventmanagers = new HashSet<Eventmanager>(0);
private Set<Sensor> sensors = new HashSet<Sensor>(0);
private Set<Personevent> personevents = new HashSet<Personevent>(0);

    public Event() {
    }



     @Id 

    

    @Column(name="event_id", nullable=false)
    public long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(long eventId) {
        this.eventId = eventId;
    }

    

    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)

    @Column(name="startdate", length=29)
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    @Temporal(TemporalType.TIMESTAMP)

    @Column(name="enddate", length=29)
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

@OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="event")
    public Set<Attendance> getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set<Attendance> attendances) {
        this.attendances = attendances;
    }

@OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="event")
    public Set<Eventmanager> getEventmanagers() {
        return this.eventmanagers;
    }
    
    public void setEventmanagers(Set<Eventmanager> eventmanagers) {
        this.eventmanagers = eventmanagers;
    }

@OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="event")
    public Set<Sensor> getSensors() {
        return this.sensors;
    }
    
    public void setSensors(Set<Sensor> sensors) {
        this.sensors = sensors;
    }

@OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="event")
    public Set<Personevent> getPersonevents() {
        return this.personevents;
    }
    
    public void setPersonevents(Set<Personevent> personevents) {
        this.personevents = personevents;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof Event) )
		 return false;

		 Event that = ( Event ) o;

		 return (this.getEventId()==that.getEventId());

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + (int) this.getEventId();

         return result;
     }


}

