/*Copyright (c) 2015-2016 presense@presense.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with presense@presense.com*/

package com.presense.dadjf5a027tja9;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * PersoneventId generated by hbm2java
 */
@Embeddable
public class PersoneventId  implements java.io.Serializable
 {


private long eventId;
private long personId;

    public PersoneventId() {
    }




    

    @Column(name="event_id", nullable=false)
    public long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(long eventId) {
        this.eventId = eventId;
    }

    

    @Column(name="person_id", nullable=false)
    public long getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(long personId) {
        this.personId = personId;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof PersoneventId) )
		 return false;

		 PersoneventId that = ( PersoneventId ) o;

         return (this.getEventId()==that.getEventId())
 && (this.getPersonId()==that.getPersonId());

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + (int) this.getEventId();
         result = 37 * result + (int) this.getPersonId();

         return result;
     }


}

