/*Copyright (c) 2015-2016 presense@presense.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with presense@presense.com*/

package com.presense.dadjf5a027tja9;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * Sensor generated by hbm2java
 */
@Entity
@Table(name="sensor"
    ,schema="public"
)
public class Sensor  implements java.io.Serializable
 {


private long sensorId;
private String name;
private Event event;

    public Sensor() {
    }



     @Id 

    

    @Column(name="sensor_id", nullable=false)
    public long getSensorId() {
        return this.sensorId;
    }
    
    public void setSensorId(long sensorId) {
        this.sensorId = sensorId;
    }

    

    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="event", nullable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof Sensor) )
		 return false;

		 Sensor that = ( Sensor ) o;

		 return (this.getSensorId()==that.getSensorId());

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + (int) this.getSensorId();

         return result;
     }


}

